[package]
name = "user_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.28.0"

solana-program = "1.9.4"
borsh = "0.9.0"
[lib]
crate-type = ["cdylib", "lib"]