[features]
seeds = false
skip-lint = false
[programs.localnet]
user_input = "UhH9QdWTjFedFNtasBBaxwP7A52JPipkVMqBZuLR6QB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/home/kneelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
