[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "Cpos2iPMq4qheJDaM2NxSk5XABKBHeGdxYbzDh7WrVtT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kneelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
