[features]
seeds = false
skip-lint = false
[programs.localnet]
program4 = "Ek1JVWEd9uPvWfGgZ1RArqz6ZzB2MvppRmmzmE4vRUgz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kneelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
